/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'commercial' : IDL.Null,
  'events' : IDL.Null,
  'weddings' : IDL.Null,
  'portraits' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientSelection = IDL.Record({
  'customerNote' : IDL.Text,
  'selectedPhotoIds' : IDL.Vec(IDL.Text),
  'submittedAt' : IDL.Int,
  'galleryId' : IDL.Text,
});
export const GalleryPhoto = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
});
export const ClientGallery = IDL.Record({
  'id' : IDL.Text,
  'token' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'accessCode' : IDL.Opt(IDL.Text),
  'photos' : IDL.Vec(GalleryPhoto),
});
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'category' : Category,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceRange' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ClientGalleryPublic = IDL.Record({
  'id' : IDL.Text,
  'token' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'photos' : IDL.Vec(GalleryPhoto),
});
export const GalleryAccessResult = IDL.Record({
  'hasCode' : IDL.Bool,
  'selection' : IDL.Opt(ClientSelection),
  'gallery' : IDL.Opt(ClientGalleryPublic),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhoto' : IDL.Func([IDL.Text, Category, ExternalBlob], [], []),
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClientGallery' : IDL.Func(
      [IDL.Text, IDL.Vec(ExternalBlob), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteClientGallery' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'getAbout' : IDL.Func([], [IDL.Text], ['query']),
  'getAllClientGalleries' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'selection' : IDL.Opt(ClientSelection),
            'gallery' : ClientGallery,
          })
        ),
      ],
      ['query'],
    ),
  'getAllClientSelections' : IDL.Func(
      [],
      [IDL.Vec(ClientSelection)],
      ['query'],
    ),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientGalleryByToken' : IDL.Func(
      [IDL.Text],
      [GalleryAccessResult],
      ['query'],
    ),
  'getClientGallerySelection' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ClientSelection)],
      ['query'],
    ),
  'getContactInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getPhotosByCategory' : IDL.Func([Category], [IDL.Vec(Photo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitClientSelection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateAbout' : IDL.Func([IDL.Text], [], []),
  'updateContactInfo' : IDL.Func([IDL.Text], [], []),
  'updateService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'verifyGalleryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'commercial' : IDL.Null,
    'events' : IDL.Null,
    'weddings' : IDL.Null,
    'portraits' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientSelection = IDL.Record({
    'customerNote' : IDL.Text,
    'selectedPhotoIds' : IDL.Vec(IDL.Text),
    'submittedAt' : IDL.Int,
    'galleryId' : IDL.Text,
  });
  const GalleryPhoto = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
  });
  const ClientGallery = IDL.Record({
    'id' : IDL.Text,
    'token' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'accessCode' : IDL.Opt(IDL.Text),
    'photos' : IDL.Vec(GalleryPhoto),
  });
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'category' : Category,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceRange' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ClientGalleryPublic = IDL.Record({
    'id' : IDL.Text,
    'token' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'photos' : IDL.Vec(GalleryPhoto),
  });
  const GalleryAccessResult = IDL.Record({
    'hasCode' : IDL.Bool,
    'selection' : IDL.Opt(ClientSelection),
    'gallery' : IDL.Opt(ClientGalleryPublic),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhoto' : IDL.Func([IDL.Text, Category, ExternalBlob], [], []),
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClientGallery' : IDL.Func(
        [IDL.Text, IDL.Vec(ExternalBlob), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteClientGallery' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'getAbout' : IDL.Func([], [IDL.Text], ['query']),
    'getAllClientGalleries' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'selection' : IDL.Opt(ClientSelection),
              'gallery' : ClientGallery,
            })
          ),
        ],
        ['query'],
      ),
    'getAllClientSelections' : IDL.Func(
        [],
        [IDL.Vec(ClientSelection)],
        ['query'],
      ),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientGalleryByToken' : IDL.Func(
        [IDL.Text],
        [GalleryAccessResult],
        ['query'],
      ),
    'getClientGallerySelection' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ClientSelection)],
        ['query'],
      ),
    'getContactInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getPhotosByCategory' : IDL.Func([Category], [IDL.Vec(Photo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitClientSelection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateAbout' : IDL.Func([IDL.Text], [], []),
    'updateContactInfo' : IDL.Func([IDL.Text], [], []),
    'updateService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'verifyGalleryCode' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };