/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'commercial' : null } |
  { 'events' : null } |
  { 'weddings' : null } |
  { 'portraits' : null };
export interface ClientGallery {
  'id' : string,
  'token' : string,
  'name' : string,
  'createdAt' : bigint,
  'accessCode' : [] | [string],
  'photos' : Array<GalleryPhoto>,
}
export interface ClientGalleryPublic {
  'id' : string,
  'token' : string,
  'name' : string,
  'createdAt' : bigint,
  'photos' : Array<GalleryPhoto>,
}
export interface ClientSelection {
  'customerNote' : string,
  'selectedPhotoIds' : Array<string>,
  'submittedAt' : bigint,
  'galleryId' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryAccessResult {
  'hasCode' : boolean,
  'selection' : [] | [ClientSelection],
  'gallery' : [] | [ClientGalleryPublic],
}
export interface GalleryPhoto {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
}
export interface Photo {
  'id' : string,
  'title' : string,
  'blob' : ExternalBlob,
  'category' : Category,
}
export interface Service {
  'id' : string,
  'name' : string,
  'description' : string,
  'priceRange' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<[string, Category, ExternalBlob], undefined>,
  'addService' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClientGallery' : ActorMethod<
    [string, Array<ExternalBlob>, [] | [string]],
    string
  >,
  'deleteClientGallery' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'getAbout' : ActorMethod<[], string>,
  'getAllClientGalleries' : ActorMethod<
    [],
    Array<{ 'selection' : [] | [ClientSelection], 'gallery' : ClientGallery }>
  >,
  'getAllClientSelections' : ActorMethod<[], Array<ClientSelection>>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientGalleryByToken' : ActorMethod<[string], GalleryAccessResult>,
  'getClientGallerySelection' : ActorMethod<[string], [] | [ClientSelection]>,
  'getContactInfo' : ActorMethod<[], string>,
  'getPhotosByCategory' : ActorMethod<[Category], Array<Photo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitClientSelection' : ActorMethod<
    [string, string, Array<string>, string],
    undefined
  >,
  'updateAbout' : ActorMethod<[string], undefined>,
  'updateContactInfo' : ActorMethod<[string], undefined>,
  'updateService' : ActorMethod<[string, string, string, string], undefined>,
  'verifyGalleryCode' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];